version: '3.9'
services:
  client:
    image: mpx/client:local
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=test-secret
    networks:
      - mpx-w1
  server:
    image: mpx/server:local
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - JWT_SECRET=test-secret
    networks:
      - mpx-w1

networks:
  mpx-w1: {}
